name: Deploy FastAPI to VM

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  ssh:
    name: script-runner
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild & Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            # Check if the repository is already cloned
            if [ ! -d "Faralpha" ]; then
                # Clone the repository if not already cloned
                git clone https://github.com/dv2202/Faralpha.git
            fi

            # Move into the cloned directory
            cd Faralpha

            # Run the bash script
            bash deploy.sh
