name: Deploy FastAPI to VM

on:
  workflow_dispatch:

jobs:
  ssh:
    name: script-runner
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild & Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd Faralpha

            # Run the bash script
            bash deploy.sh
